<a href="https://colab.research.google.com/github/andrewhone1/Hello-World/blob/main/BA101_Lab_2_Tasks_Andrew_Hone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1

In [ ]:
import numpy as np

In [ ]:
data = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

arr1 = np.array(data)

print(arr1)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
arr2 = np.arange(10, 50)
print(arr2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
arr3 = np.random.random((3, 3, 3))
print(arr3)

[[[0.74181203 0.43467563 0.56479261]
  [0.68527487 0.05349238 0.24187847]
  [0.12538688 0.47183287 0.71143084]]

 [[0.35749755 0.51446781 0.35776226]
  [0.24328628 0.51182894 0.42208624]
  [0.4228863  0.35673892 0.54942308]]

 [[0.64500128 0.60964062 0.14556678]
  [0.00860499 0.21311787 0.69836114]
  [0.4159754  0.74015013 0.80066054]]]


# Task 2

In [ ]:
result = np.array(10) / np.array(5)
print(result)
result.dtype

2.0


dtype('float64')

In [ ]:
result = np.array(10) // np.array(3)
print(result)
result.dtype

3


dtype('int32')

In [ ]:
result = np.array("5").astype(int).astype(float)
print(result)
result.dtype

5.0


dtype('float64')

# Task 3

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [ ]:
a + b

array([[11, 13, 15],
       [17, 19, 21]])

In [ ]:
a + 2*b

array([[21, 24, 27],
       [30, 33, 36]])

In [ ]:
a > b

array([[False, False, False],
       [False, False, False]])

# Task 4

In [ ]:
import numpy as np

arr = np.array([[1,2,3], [4,5,6], [7,8,9]])

arr2 = arr[2:3] [:1]

print(arr2)
print(np.shape(arr2))

[[7 8 9]]
(1, 3)


In [ ]:
arr3 = arr[0][:]

print(arr3)
print(np.shape(arr3))

[1 2 3]
(3,)


In [ ]:
arr4 = arr[:1, 2]

print(arr4)
print(np.shape(arr4))

[3]
(1,)


# Task 5

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([11, 12, 13, 14, 15, 16, 17, 18])
#Unary functions
print(np.sqrt(a))
print(np.sqrt(b))

print(np.exp(a))
print(np.exp(b))

print(np.ceil(a))
print(np.floor(b))

print(np.isnan(a))
print(np.isnan(b))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[3.31662479 3.46410162 3.60555128 3.74165739 3.87298335 4.
 4.12310563 4.24264069]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[5.98741417e+04 1.62754791e+05 4.42413392e+05 1.20260428e+06
 3.26901737e+06 8.88611052e+06 2.41549528e+07 6.56599691e+07]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[11. 12. 13. 14. 15. 16. 17. 18.]
[False False False False False False False False False False]
[False False False False False False False False]


In [ ]:
#Binary Ufunc
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
b = np.array([11, 12, 13, 14, 15, 16, 17, 18, 19,20])

np.add(a, b)


array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [ ]:
np.multiply(a, b)

array([ 11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [ ]:
np.maximum(a, b)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.minimum(a, b)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Task 6

In [ ]:
import pandas as pd

In [ ]:
x = pd.Series([2, 4, 6, 8, 10])
y = pd.Series([1, 3, 5, 7, 9])

print(x.add(y))


0     3
1     7
2    11
3    15
4    19
dtype: int64


In [ ]:
print(x.subtract(y))

0    1
1    1
2    1
3    1
4    1
dtype: int64


In [ ]:
print(x.multiply(y))

0     2
1    12
2    30
3    56
4    90
dtype: int64


In [ ]:
print(x.divide(y))

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


# Task 7